apiVersion: v1
kind: Secret

metadata:
  name: db-secret

data:
  db-root-password: bVBhc3M= # Base64 encoded value of 'mPass'
  db-admin-password: bVBhc3M= # This file should not be committed to the repository
